### ISSUE TITLE
Design the new landing page

### ISSUE THREAD

**Issue by Wimsy113** [zinc-collective/www.gormonjee.com#1]
**Old Site**
http://gormonjee.com/

**Figma**
https://www.figma.com/file/eqYbV9TT0WFIFz4JQKy4sX/Gormonjee?node-id=0%3A1

Trying to go for something cool and modern while pulling from the original site for inspiration. Would love to hear thoughts on this.

**Comment by zspencer** [comment]
@zinc-collective/gormonjee-maintainers - Is there next steps that I could take to carry this forward? I'm going through the issues that I haven't opened and haven't had activity in a while and trying to figure out what tiny thing I can do to carry them forward to help folks build momentum.

**Comment by zspencer** [comment]
@zinc-collective/gormonjee-maintainers - I've configured the DNS so that https://gormonjee.zinc.coop goes to the site being built here.

@maximegalon5  - Is the site currently hosted at https://gormonjee.zinc.coop "good enough" to switch over to from www.gormonjee.com or do you want other changes before we do so?

**Comment by maximegalon5** [comment]
Yes. Thank you! This is great. It is very useful to have a link that I can click and see online.

**Comment by zspencer** [comment]
@maximegalon5 - Would you mind either A) editing this ticket with checkboxes for the bits and bobs of the www.gormonjee.com website that you want changed or B) closing it and creating new tickets for the changes you'd like to see? 

I'm trying to take _just_ enough initiative to keep things moving forward, and putting the ball back in the stakeholders court to clearly define small, specific steps towards what they want to exist so that folks can coalesce around the project and bring tiny, useful changes.

**Comment by maximegalon5** [comment]
I confirm that production matches the intended change and hence closing the issue. Thanks @zspencer and @Wimsy113
